all: go1 go2 go3 go4 go5 go6 go0

go1:
	inkscape --export-png=component1.png component1.svg
go2:
	inkscape --export-png=component2.png component2.svg
go3:
	inkscape --export-png=component3.png component3.svg
go4:
	inkscape --export-png=component4.png component4.svg
go5:
	inkscape --export-png=component5.png component5.svg
go6:
	inkscape --export-png=component6.png component6.svg
go0:
	inkscape --export-png=essentials.png essentials.svg

